name: flutter_app_rebrand
description: Rebrand your Flutter application using one command from terminal

version: 1.0.3

maintainer: Sarjeet Sandhu

homepage: https://github.com/sarj33t/flutter_app_rebrand

funding:
  - https://www.buymeacoffee.com/sarj33t

environment:
  sdk: ^3.5.3

dependencies:
  image: ^4.5.3