name: flutter_app_rebrand

description: Rebrand your Flutter application using one command from terminal

version: 1.0.0

maintainer: Sarjeet Sandhu

publisher: sarj33t.com

homepage: https://github.com/sarj33t/flutter_app_rebrand

environment:
  sdk: ^3.5.3

dependencies:
  image: ^4.2.0