name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package_functionality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable

      - name: Create a new Flutter project
        run: |
          flutter create test_app
          cd test_app

      - name: Add your package to pubspec.yaml
        run: |
          cd test_app
          sed -i '/dev_dependencies:/a\  flutter_app_rebrand:\n    path: ../' pubspec.yaml

      - name: Get dependencies
        run: |
          cd test_app
          flutter pub get

      - name: Create rebrand.json
        run: |
          echo '{"packageName": "com.sarj33t.app", "launcherIconPath": "", "appName": "Panda App" }' > test_app/rebrand.json

      - name: Run package rename command
        run: |
          cd test_app
          dart run flutter_app_rebrand:main rebrand.json

      - name: Check Android files
        run: |
          cd test_app
          grep -q "applicationId = \"com.sarj33t.app\"" android/app/build.gradle || exit 1
          grep -q "package com.sarj33t.app" android/app/src/main/kotlin/com/sarj33t/app/MainActivity.kt || exit 1

      - name: Check iOS files
        run: |
          cd test_app
          grep -q "PRODUCT_BUNDLE_IDENTIFIER = com.sarj33t.app" ios/Runner.xcodeproj/project.pbxproj || exit 1

      - name: Run Flutter analyze
        run: |
          cd test_app
          flutter analyze